TreeComments/TreeComments/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('notes.urls')),
]

TreeComments/notes/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', index),
    path('article/<int:article_id>/', getArticle),
]

TreeComments/notes/models.py
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey

# Create your models here.

class Articles(models.Model):
    title = models.CharField(max_length=150)
    content = models.TextField(blank=True)
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Статья'
        verbose_name_plural = 'Статьи'


class Comments(MPTTModel):
    article = models.ForeignKey(Articles, on_delete=models.CASCADE, related_name='comments')
    autor = models.CharField(max_length=150, verbose_name='Автор комментария')
    text = models.TextField(verbose_name='Текст комментария')
    parent = TreeForeignKey('self', on_delete=models.CASCADE,
                            null=True, blank=True, related_name='children')

    def __str__(self):
        return self.autor

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

TreeComments/notes/forms.py
from django import forms

from .models import Comments
from mptt.forms import TreeNodeChoiceField


class CommentFrom(forms.ModelForm):
    parent = TreeNodeChoiceField(queryset=Comments.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['parent'].widget.attrs.update(
            {'display': 'none'})
        self.fields['parent'].label = ''
        self.fields['parent'].required = False

    class Meta:
        model = Comments
        fields = ('autor', 'parent', 'text')

TreeComments/notes/views.py
from django.shortcuts import render, get_object_or_404

from .models import Articles, Comments
from .forms import CommentFrom

# Create your views here.
def index(request):
    articles = Articles.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, template_name='notes/index.html',context=context)


def getArticle(request, article_id):  # Комментарии должны выводиться тут
    article = Articles.objects.filter(id=article_id)  # Комеентарии надо выгрузить

    if request.method == 'POST':
        comment_form = CommentFrom(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.article_id = article_id
            new_comment.save()

    comment_form = CommentFrom()
    comments = Comments.objects.filter(article_id=article_id)
    context = {
        'article': article,
        'form': comment_form,
        'comments': comments,
    }
    return render(request, template_name='notes/article.html', context=context)

TreeComments/notes/templates/notes/article.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article.title</title>
    <style>
        .articles{
        border: 2px solid black;
        margin-top: 15px;
        background-color: #A9A9A9;
        }
        .form_add_comment{
            border: 2px solid black;
            margin-top:5px;
        }
        .form_add_comment div{
            margin-left: 15px;
        }
        .form_add_comment p{
            margin: 1px;
        }
        .form_add_comment h2{
            margin: 3px;
        }

        .comment{
            background-color: #E0E0E0;
            border-radius: 15px;
            margin-top: 20px;

        }
        .comment div{
            margin-left: 20px;
        }
    </style>
</head>
<body>

{% for article in article %}
    <div class="articles">
        <div style="margin-left: 15px">
            <h3>{{article.title}}</h3>
            <p>{{article.content}}</p>
        </div>
    </div>
{% endfor %}

<hr>
<div  class="form_add_comment" >
    <div>
        <h2>Добавить новый комментарий</h2>
        <form action="." method="post">
            <p >Ваше имя:</p>
            {{ form.autor }}
            <p>Ваш комментарий:</p>
            {{ form.text }}
            {% csrf_token %}
            <p><input type="submit" value="Добавить"></p>
        </form>
    </div>
</div>


<h3>Комментарии к статье</h3>


<!--Этот цикл выгружает комментарии-->
{% load mptt_tags %}
<div>
    {% recursetree comments %}  <!--    Этот цикл выгружает только комментарии, у которых нет родителей-->
    <div  class="comment" id="{{ node.id }}">
        <div>
            <h3>{{ node.autor }}</h3>
            <p>{{ node.text }}</p>
            <button class="button" onclick="myFunction({{ node.id }})">Ответить</button>
        </div>
    </div>
    <!-- Выводим все дочерние комментарии  -->
    {% if not node.is_leaf_node %}
        <div style="margin-left: 20px">
          {{ children }}
        </div>
        {% endif %}
    {% endrecursetree %}
</div>

<script>
  function formExit() {
    document.getElementById("newForm").remove();
  }

  function myFunction(id) {
    if (document.contains(document.getElementById("newForm"))) {
      document.getElementById("newForm").remove();
    }

    var d1 = document.getElementById(id);
    d1.insertAdjacentHTML('afterend',
      '<form action="." id="newForm" method="post"> \
        <p>Ваше имя:</p>\
        <input type="text" name="autor" maxlength="150" required="" id="id_autor">\
        <select name="parent" style="display: none;" id="id_parentt"> \
                <option value="' + id + '" selected="' + id + '"></option> \
                </select> \
        <p>Ваш комментарий:</p>\
        <textarea name="text" cols="40" rows="10" required="" id="id_text"></textarea>\
        <input type="hidden" name="csrfmiddlewaretoken" value="m8D9CsbDhu1VTNu3NUTkVx6cn1PCkqycrJPQUjaPyrDZtPV23COsTGuGcQjw12CC">\
        {% csrf_token %} \
        <p><input type="submit" value="Ответить"></p>\
        </form>');

    //document.querySelector('#id_parentt [value="' + id + '"]').selected = true;
  }

  $('#myForm').trigger("reset");
</script>

</body>
</html>

TreeComments/notes/templates/notes/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список статей</title>
</head>
<body>
<h1>Список статей</h1>
{% for article in articles %}
    <div style="border-radius: 15px;  border: 2px solid black; margin-top: 15px">
        <div style="margin-left: 15px">
            <h3>{{article.title}}</h3>
            <p>{{article.content}}</p>
            <div style="margin-bottom: 15px"><a href="/article/{{ article.id }}">Прочитать подробнее</a></div>
        </div>
    </div>
{% endfor %}
</body>
</html>